env:
  browser: true
  es2021: true
  mocha: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-var: error
  semi: error
overrides:
  - files: "webpack.config.js"
    env:
      node: true
